# Generated by Django 3.0.7 on 2020-06-09 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_auto_20200609_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(blank=True, null=True, related_name='article', to=settings.AUTH_USER_MODEL),
        ),
    ]
